swipe:
  3:
    right:
      command: 'xdotool key ctrl+Shift+Tab'
    left:
      command: 'xdotool key ctrl+Tab'
    up:
      command: 'xdotool key ctrl+t'
    down:
      command: 'xdotool key ctrl+w'
  4:
    left:
      command: 'xdotool key super+alt+Right'
    right:
      command: 'xdotool key super+alt+Left'
    up:
      command: 'xdotool key super'
    down:
      command: 'xdotool key alt+F4'
pinch:
  in:
    command: 'xdotool key super'
  out:
     command: 'xdotool key super+a'

threshold:
  swipe: 0.3
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
