swipe:
  3:
    right:
      command: 'xdotool key ctrl+Shift+Tab'
    left:
      command: 'xdotool key ctrl+Tab'
    up:
      command: 'xdotool key ctrl+t'
    down:
      command: 'xdotool key ctrl+w'
  4:
    left:
      command: 'xdotool key alt+Tab'
    right:
      command: 'xdotool key alt+Tab'
    up:
      command: 'xdotool key alt+F10'
    down:
      command: 'xdotool key alt+F4'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
    threshold: 0.1
  out:
     command: 'xdotool key ctrl+minus'
     threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
